"""Application constants."""

# User roles
ROLE_ADMIN = "admin"
ROLE_HR = "hr"
ROLE_MANAGER = "manager"
ROLE_EMPLOYEE = "employee"

USER_ROLES = [ROLE_ADMIN, ROLE_HR, ROLE_MANAGER, ROLE_EMPLOYEE]

# Attendance status
ATTENDANCE_PRESENT = "present"
ATTENDANCE_ABSENT = "absent"
ATTENDANCE_LEAVE = "leave"
ATTENDANCE_HALF_DAY = "half_day"

ATTENDANCE_STATUS = [
    ATTENDANCE_PRESENT,
    ATTENDANCE_ABSENT,
    ATTENDANCE_LEAVE,
    ATTENDANCE_HALF_DAY,
]

# Leave status
LEAVE_PENDING = "pending"
LEAVE_APPROVED = "approved"
LEAVE_REJECTED = "rejected"
LEAVE_CANCELLED = "cancelled"

LEAVE_STATUS = [LEAVE_PENDING, LEAVE_APPROVED, LEAVE_REJECTED, LEAVE_CANCELLED]

# Leave types
LEAVE_CASUAL = "casual"
LEAVE_SICK = "sick"
LEAVE_PERSONAL = "personal"
LEAVE_MATERNITY = "maternity"
LEAVE_PATERNITY = "paternity"

LEAVE_TYPES = [LEAVE_CASUAL, LEAVE_SICK, LEAVE_PERSONAL, LEAVE_MATERNITY, LEAVE_PATERNITY]
